# site properties and page defaults
title: ASU-IDI
show-title: false
subtitle: The Intelligent Data Infrastructure Lab at Arizona State University
description: An engaging 1-3 sentence description of your lab.
header: images/background.png
footer: images/background.png

# site social media and other links
links:
  email: zhichao.cao@asu.edu
  google-scholar: VI4vH9UAAAAJ
  github: asu-idi

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_research_data
  - scope:
      type: "research"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  # generate page for each research post
  research:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
