- id: https://doi.org/10.1145/3655038.3665946
  conference: ACM HotStorage 2024
  buttons:
    - type: download
      link: ./../publications/files/HS24_ZNS_PersistentCache.pdf

- id: https://doi.org/10.1145/3655038.3665954
  conference: ACM HotStorage 2024
  buttons:
    - type: download
      link: ./../publications/files/HS24_GPT_Project.pdf

- title: "Prophet: Optimizing LSM-Based Key-Value Store on ZNS SSDs with File Lifetime Prediction and Compaction Compensation"
  authors:
    - Gaoji Liu
    - Chongzhuo Yang
    - Qiaolin Yu
    - Chang Guo
    - Wen Xia
    - Zhichao Cao
  conference: MSST 2024
  date: '2024-06-03'

- title: "SAS-Cache: A Semantic-Aware Secondary Cache for LSM-based Key-Value Stores"
  authors:
    - Zhang Cao
    - Chang Guo
    - Ziyan Lv
    - Anand Ananthabhotla
    - Zhichao Cao
  conference: MSST 2024
  date: '2024-06-03'

- id: https://doi.org/10.1145/3654927
  conference: ACM SIGMOD 2024

- id: https://doi.org/10.1109/ICCD58817.2023.00050
  title: "SMRTS: A Performance and Cost-Effectiveness Optimized SSD-SMR Tiered File System with Data Deduplication"
  authors:
    - Zhichao Cao
    - Hao Wen
    - Fenggang Wu
    - David H.C. Du
  date: '2023-11-06'
  conference: IEEE ICCD 2023

- id: https://doi.org/10.1109/ICCD58817.2023.00041
  title: "K8sES: Optimizing Kubernetes with Enhanced Storage Service-Level Objectives"
  authors:
    - Hao Wen
    - Zhichao Cao
    - Bingzhe Li
    - David H.C. Du
    - Ayman Abouelwafa
    - Doug Voigt
    - Shiyong Liu
    - Jim Diehl
    - Fenggang Wu
  date: '2023-11-06'
  conference: IEEE ICCD 2023

- id: https://doi.org/10.1145/3653924.3653935
  conference: ACM DSDE 2024

- id: https://doi.org/10.1109/TC.2024.3485238
  conference: IEEE Transactions on Computers
  date: '2024-12-08'
  authors:
    - Yixun Wei
    - Zhichao Cao
    - David H.C. Du

- id: https://doi.org/10.1145/3694715.3695953